package com.example.demo.model;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    private Integer id;



	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.gradeName
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    private String label;



	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
 

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.gradeName
     *
     * @return the value of grade.gradeName
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.gradeName
     *
     * @param gradename the value for grade.gradeName
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */

}