package com.example.demo.model;

public class TeacherType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_type.id
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_type.type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_type.id
     *
     * @return the value of teacher_type.id
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_type.id
     *
     * @param id the value for teacher_type.id
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_type.type
     *
     * @return the value of teacher_type.type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_type.type
     *
     * @param type the value for teacher_type.type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }
}