package com.example.demo.dao;

import com.example.demo.model.TeacherType;
import com.example.demo.model.TeacherTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int countByExample(TeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int deleteByExample(TeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int insert(TeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int insertSelective(TeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    List<TeacherType> selectByExample(TeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    TeacherType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") TeacherType record, @Param("example") TeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int updateByExample(@Param("record") TeacherType record, @Param("example") TeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_type
     *
     * @mbggenerated Thu Jun 28 15:34:22 CST 2018
     */
    int updateByPrimaryKey(TeacherType record);
}